### ISSUE TITLE
ComEd

### ISSUE THREAD

**Issue by mluckolson** [ScottEvtuch/HubitatComEd#1]
Hey Scott, hope you don’t mind, but as a com-Ed customer and avid Hubitat user, I tried your code.  Works great overall, except I keep getting this one error in the logs every hour.  Any ideas?

Failed to calculate state: java.lang.NullPointerException: Cannot get property 'extreme' on null object

**Comment by ScottEvtuch** [comment]
When you go to the device in the hubitat web interface what do you see for the values of the state variables? It should look something like this:

```
fiveMinPrice : 4.0
currentPrices : [3.8, 4.7, 1.6, 3.7]
currentState : {high=-1, low=1, state=Low, extreme=-1}
predictions : [[6.2], [6.0], [5.6], [5.4], [5.4], [5.4], [6.2], [6.7], [7.1], [6.8], [6.5], [6.1], [5.5], [4.8], [5.1], [4.7], [5.1], [5.3], [5.8], [8.3], [10.0], [7.9], [7.6], [6.1]]
```

**Comment by mluckolson** [comment]
My device looks like this.  I get a new CurrentPrice every few minutes. 

![Screen Shot 2022-04-11 at 8 38 49 PM](https://user-images.githubusercontent.com/29029650/162861539-40d55722-b14a-4a71-a378-848355b689b3.png)

**Comment by ScottEvtuch** [comment]
Yeah that's strange you should have a currentState value being populated each time the price is updated. Have you changed any of the settings from their defaults? If you hit the "Save Preferences" button it should recreate all of the proper state variables.

**Comment by mluckolson** [comment]
No I don't think I changed any of the default settings.  I did just Save Preferences, and then currentState showed up under State Variables.  Let's see if the errors now go away.  Will monitor.

BTW, I obviously get what Current Price is, but I don't fundamentally understand what you were going after regarding Prediction.  What's the idea there?

**Comment by ScottEvtuch** [comment]
I personally use the "Predicted" state to trigger my air conditioner to run at a lower temperature set point than it would normally. Basically, if the energy price is predicted to be high in the near future, run the air conditioner to try to cool the house before the price goes up and the air conditioner is cycled off. The extra cooling ahead of time allows the house to stay a more reasonable temperature while avoiding running the air conditioner during peak prices.

**Comment by mluckolson** [comment]
Oh that is frickin brilliant.  I was using the currentprice to notify my wife and me about spike periods, during which we were more careful with energy-guzzling devices.  But your use-case is better.  If you don't mind me asking, what's your prediction methodology (high level)?

**Comment by ScottEvtuch** [comment]
I just pull the predictions directly from ComEd's website: https://hourlypricing.comed.com/live-prices/

I actually do have to do some weird number-crunching for the current hourly price because ComEd charges you for the _whole hour_ based on the average of all of the 5 minute prices for that hour. You don't actually know what the hourly price is going to be for 1-2pm at 1:05pm, for example. I have to make an educated guess based on the prices I know so far and the prediction.

**Comment by mluckolson** [comment]
Gotcha -- makes sense.   Thanks for the help.

**Comment by mluckolson** [comment]
Hey Scott, I was just about to write a few rules in RM to use predicted pricing to manage some appliance behavior in our home.    Until I realized that the Predicted Pricing metrics are not attributes; they are just states.  Would it be too much trouble to expose those values as attributes in the device driver?  I'd do it myself but I'm not a developer -- no skillz!  TIA...

**Comment by ScottEvtuch** [comment]
The predictions are exposed in the HighThreshold and LowThreshold attributes. They will change from "Untriggered" to "Predicted" and then to "Triggered". Were you looking for some other specific type of functionality?

**Comment by mluckolson** [comment]
Idk it's probably not a big deal, but I was thinking it would be handy to have the fiveMinPrice exposed, but I take your point about the three Threshold attributes.  Fair to say that only one can be Triggered at a time and only one can be Predicted at a time?

**Comment by ScottEvtuch** [comment]
fiveMinPrice is exposed via the "CurrentPrice" attribute. I guess in theory I could also just expose a PrediectedPrice attribute that you could use instead of relying on the predicted state.

Actually looking through the code I only allow "Predicted" for High and Extreme prices. The predictions function independently so you could have a both High and Extreme both predicted.

**Comment by mluckolson** [comment]
Oh I misunderstood.  I thought CurrentPrice=now-ish and FiveMinPrice=future, but sounds like that's wrong.  If you could expose a Predicted Price in addition to Current, it'd be great.  What's you look-forward time period for prediction?

**Comment by mluckolson** [comment]
My device looks like this.  I get a new CurrentPrice every few minutes.
